### ISSUE TITLE
Altering the update rate of MCTargetStrategy via NavigatorParameters

### ISSUE THREAD

**Issue by Flame10A** [CitizensDev/CitizensAPI#13]
Would it be possible to have an update rate property in NavigatorParameters? Would be helpful to have the flexibility, having seen the effects of CitizensDev/Citizens2@3b295faae086397f955892eec4dc2cbccb30dce8.

**Comment by mcmonkey4eva** [comment]
And perhaps a configurable setting in the config for a better default.

--

@fullwall What do you think?

**Comment by fullwall** [comment]
Yes, sure. I'll add it.

**Comment by fullwall** [comment]
Done

**Comment by Flame10A** [comment]
Thanks, much appreciated!
