### ISSUE TITLE
[Question] Setup NPC with "default" speed

### ISSUE THREAD

**Issue by brainscript** [CitizensDev/CitizensAPI#15]
I'm currently working on a simple pet plugin based on Citizens, because I don't want to work with NMS stuff and reflections (or I'm just to lazy) ...

```
public static void createPet(Player p, PetType pt) {
        NPCRegistry reg = CitizensAPI.getNPCRegistry();
        NPC npc = reg.createNPC(pt.getType(), "MyNPC");
        npc.spawn(p.getLocation());
        npc.setName("§e" + p.getName() + "§6's " + pt.getName());
        npc.addTrait(Controllable.class);
        setPet(p, npc);
    }
```
*(`PetType` contains all variants of pets you can choose.)*

When I spawn a cow using this method, the cow is moving **extremely** slow (especially when riding it). Using `/npc create TEST --type Cow` and `/npc controllable` the cow is perfect. But how can I achieve this with the API?

**Comment by fullwall** [comment]
Sorry, missed this. 
```
npc.getNavigator().getDefaultParameters().speedModifier(new_pct)
```
