### ISSUE TITLE
EntityExplodeEvent with NPCs

### ISSUE THREAD

**Issue by MarkehMe** [CitizensDev/CitizensAPI#16]
How can we detect an EntityExplodeEvent with NPCs? 

There appears to be a death event, but this doesn't specify if it was by explosion (and no way to change how the explosion works - i.e. blocks being exploded) 

None of these events are called on explosion:
 - NPCCombustEvent
 - EntityExplodeEvent
 - NPCRightClickEvent (right click creeper NPC to cause explosion)
 - NPCDespawnEvent

Any pointers? 😄

**Comment by mcmonkey4eva** [comment]
What exactly is causing your NPC to explode?

**Comment by MarkehMe** [comment]
Flint and Steel.

However.. I'm an idiot, apologies. I missed over something in my own codebase, causing the events to not register properly.

**Comment by MarkehMe** [comment]
Side note: ```NPCDeathEvent``` is not getting called when a NPC Creeper explodes:

```java
	public void spawnAt(final Location location) {
		final NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.CREEPER, this.getMobName());
		npc.setName(this.getMobName());
		npc.setProtected(false);
		npc.addTrait(Powered.class);
		
		location.getWorld().playSound(location, Cegg.getHiss(), 3F, 1F);
		location.getWorld().playEffect(location, Effect.FIREWORKS_SPARK, 15);
		
		npc.spawn(location);

		// .. some other internal stuff happens after this that doesn't relate 

	}
```


And in my listener..


```java
	@EventHandler
	public void onNPCDeathEvent(NPCDeathEvent event) {
		Plugin.get().log("npc death event");

	}
```

It doesn't get called. 

I don't need this issue so I don't really need it, just thought I would point it out 😄 

Thanks again for taking the time to respond.
