### ISSUE TITLE
Add a way to prevent NPC from walking off blocks

### ISSUE THREAD

**Issue by KingFaris10** [CitizensDev/CitizensAPI#19]
Currently if I use Navigator#setTarget(Location) on a SkyBlock Island, the NPC falls right off if the Location is over the void. Is there a way to make the NPC stop if there is no path towards the target. If not, can you please add one if possible?

**Comment by fullwall** [comment]
You mean the teleport StuckAction?

**Comment by KingFaris10** [comment]
I know about stuck action, but how can I cancel 'setTarget'/moving?

**Comment by fullwall** [comment]
If it's moving then it found a path

**Comment by KingFaris10** [comment]
For some reason even though debug-pathfinding's true, all it says is:
`2016-08-11 23:30:37 [INFO] Unable to find Rhino classes - javascript scripts won't see non-CraftBukkit classes
2016-08-11 23:30:46 [INFO] Fetched profile f9843dd6-0a5f-4009-b451-847291bda6b3 for player KingFaris10
2016-08-11 23:30:46 [INFO] Removing 161 from skin tracker due to DespawnReason.PENDING_RESPAWN
2016-08-11 23:30:46 [INFO] Despawned 161 DespawnReason. PENDING_RESPAWN
2016-08-11 23:31:42 [INFO] Preventing further respawns of 161 due to DespawnReason.PLUGIN
2016-08-11 23:31:42 [INFO] Despawned 161 DespawnReason. PLUGIN
2016-08-11 23:31:42 [INFO] Tried to despawn 161 while already despawned.
2016-08-11 23:31:42 [INFO] Preventing further respawns of 161 due to DespawnReason.REMOVAL
2016-08-11 23:32:36 [INFO] Preventing further respawns of 162 due to DespawnReason.PLUGIN
2016-08-11 23:32:36 [INFO] Despawned 162 DespawnReason. PLUGIN
2016-08-11 23:32:36 [INFO] Tried to despawn 162 while already despawned.
2016-08-11 23:32:36 [INFO] Preventing further respawns of 162 due to DespawnReason.REMOVAL`

My issue is, using setTarget(player.getLocation()), if I'm flying over the void, it starts teleporting to me instead of staying still. (I haven't set any Stuck Action yet (haven't touched the method)).

**Comment by BlackCoyote** [comment]
debug-pathfinding is meant to show the path in game with particle effects and whatnot, If you could screenshot that path that it draws for you, we could understand the issue with it better

**Comment by mcmonkey4eva** [comment]
debug-pathfinding functions by showing fake blocks to all nearby players (flowers that highlight the pathway)

... Also, set the stuck action if it's teleporting ;-;

**Comment by fullwall** [comment]
Yes, the default stuck action is to teleport to the destination if no path was found. debug-pathfinding shows you fake flower blocks where you were pathfinding

**Comment by KingFaris10** [comment]
Oh haha, I thought debug-pathfinding writes to the debug file information on pathfinding. I don't think it showed any flowers by the way... Weird....

Right so, if I set the stuck action to:
`new StuckAction() {
				@Override
				public boolean run(NPC npc, Navigator navigator) {
					return false;
				}
			}`

It should work?

**Comment by KingFaris10** [comment]
Edit: Tested, yes it works.

**Comment by mcmonkey4eva** [comment]
I think you can also just set it to `null`

**Comment by KingFaris10** [comment]
Never mind... for some reason it slowly walks off (literally 0.25 blocks per second)

**Comment by KingFaris10** [comment]
Oh right, I'll try that.

**Comment by KingFaris10** [comment]
If anyone would like to join my test server and see what's occurring?

**Comment by mcmonkey4eva** [comment]
Could you perhaps record a video or gif?

**Comment by KingFaris10** [comment]
Yeah I'll try a video. Brb

**Comment by KingFaris10** [comment]
https://www.youtube.com/watch?v=t-DNAJtkT_s

**Comment by KingFaris10** [comment]
Looks like it, thanks for the support so far =)

**Comment by fullwall** [comment]
Looking into this

**Comment by fullwall** [comment]
Does the latest build help?

**Comment by KingFaris10** [comment]
I'm not able to test for a few hours, but I'll test soon.

**Comment by KingFaris10** [comment]
Completely forgot about this. Uhm, no, it still walks a tiny bit every second or so. However, it's no longer walking a tiny bit in my direction but for some reason, 90 degrees to my direction. (This is when I call setTarget(player.getLocation())). However, sometimes as soon as it reaches the end it walks back and tries to move towards me again.

**Comment by mcmonkey4eva** [comment]
Old issue - if still relevant, please reopen it at https://github.com/CitizensDev/Citizens2/issues
