### ISSUE TITLE
Removing nametag via. API

### ISSUE THREAD

**Issue by KingFaris10** [CitizensDev/CitizensAPI#21]
Hi, I asked 2 days ago on the Spigot thread:

> Hey, is there a way to hide the nametag on an NPC (e.g. Zombie NPC) via. the API? I know you can use a command, but I need this for a plugin. I tried npc.getEntity().setCustomNameVisible(false) but it doesn't do anything.
> Edit: I just set it to ChatColor.GRAY and it shows a small nametag (transparent black, with no text). I still want this removed.

However, I received no support. So I'll ask here, how do I do this? Why doesn't setting it to "" or null (throws Exception) work?

**Comment by mcmonkey4eva** [comment]
It should be as easy as:
```
        LivingEntity entity = (LivingEntity) npc.getEntity();
        entity.setCustomNameVisible(!entity.isCustomNameVisible());
        npc.data().setPersistent(NPC.NAMEPLATE_VISIBLE_METADATA, entity.isCustomNameVisible());
```
Based off of https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/commands/NPCCommands.java#L996

**Comment by KingFaris10** [comment]
Right, I did the first two lines but didn't know about the last one. Thanks!
