### ISSUE TITLE
Change human name without respawning it (or similar)

### ISSUE THREAD

**Issue by lucaazalim** [CitizensDev/CitizensAPI#22]
Hello,

I'm trying to spawn human NPCs that changes their names every single second. The problem is: npc.setName() respawns the entity if it is human. Is it possible to change its name without respawning it?

I know that if it isn't possible I'll have to make a hologram on the human's head. But doing that I have other problem: http://prntscr.com/d3l5zh 

Is it possible to spawn humans without nametags?

Thank you.

**Comment by mcmonkey4eva** [comment]
`/npc name` sometimes will manage to toggle the NPC's nametag.

**Comment by lucaazalim** [comment]
`/npc name` does not work with humans.

**Comment by fullwall** [comment]
Human NPCs have to be respawned to change their name as far as I'm aware (there's no 'rename player' packet). Probably best to use the EnumNameTagVisibility to hide the player name and add your hologram if you want this functionality.

**Comment by lucaazalim** [comment]
Thank you, fullwall.

**Comment by LewBr** [comment]
Nice!
