### ISSUE TITLE
Citizen's head pitch resetting

### ISSUE THREAD

**Issue by Stenlan** [CitizensDev/CitizensAPI#23]
I tried making an NPC look at me using the code
`npc.faceLocation(p.getLocation());`

It works, but only for the yaw. The pitch gets reset every tick (I think), because when I call the previously mentioned method in an EventListener for PlayerMoveEvent, the NPC looks at me, but only when I keep moving. As soon as I stop moving and thus stop calling faceLocation, the yaw is still correct but the pitch resets to make the NPC face straight forward again instead of up/down.

This also causes the following
`npc.teleport(p.getLocation())`
to only work for one tick and then have its pitch reset. Something is obviously updating the NPC every tick and then resetting the head pitch! Yaw works fine.

I am using CitizensAPI 2.0.21-SNAPSHOT
The weird thing is that LookClose on the plugin itself works fine and can set yaw/pitch fine, just not the API.

**Comment by mcmonkey4eva** [comment]
Please open issues at https://github.com/CitizensDev/Citizens2/issues not here.
