### ISSUE TITLE
NPCClickEvent wont call

### ISSUE THREAD

**Issue by Nitwel** [CitizensDev/CitizensAPI#26]
Hey,
 i recently tested out the citizens Api to check if an Player Clicks at an Npc. The problem is, it wont call, I am using the build 2.0.21-SNAPSHOT and in this version it just dont work, i tested the subevents of left and rightclicking and they are totaly fine only the upper class just sleeps.
I tested it by simply sendig a message to whoerver clicked an npc and at the fact that I only got a message form the secific classes (LeftClick and RightClick) I can tell that there must be something messed up.

I hope you will fix it and I could help you with this issue to improof the plugin.
Have a nice day, Nitwel

**Comment by mcmonkey4eva** [comment]
That's a known thing, you're meant to just use the subevents.

**Comment by Nitwel** [comment]
ok thanks, but this seems a bit confusing, at the fact that nowhere I looked this was pointed out.
Maybe you can combine these 2 subclasses in the upper so you can use all 3 of these calsses, but this is your decidion so it is just my tipp for improofments :)
