### ISSUE TITLE
Register Trait Dynamically

### ISSUE THREAD

**Issue by higgs01** [CitizensDev/CitizensAPI#28]
Due to the use of annotations isn't it possible to register Traits dynamically.

Is there any chance that it will be possible to register Traits dynamically in the future or is there a workaround for this?

**Comment by mcmonkey4eva** [comment]
What are you trying to accomplish here more specifically? 0.o

**Comment by higgs01** [comment]
I'm trying to load traits out of the database and inserting them into my Shop-System (at runtime)

**Comment by mcmonkey4eva** [comment]
You can interact with traits and their values by name - that's how the C2 saves file does it!
