### ISSUE TITLE
Null pointer exception on AbstractNPC

### ISSUE THREAD

**Issue by mvinet** [CitizensDev/CitizensAPI#29]
hello, i want use your API for make my own citizens plugin, 
but when i try to init my class who extends AbstractNPC i get an NullPointerException :
java.lang.NullPointerException
        at net.citizensnpcs.api.npc.AbstractNPC.<init>(AbstractNPC.java:84) ~[?:?]

i check the params, uuid, id, name and registry are not null :/
i'm on the 1.10

any idea ?

**Comment by fullwall** [comment]
This looks like a sign that you haven't installed Citizens2 correctly and/or (soft)depended on it
