### ISSUE TITLE
Custom Skin

### ISSUE THREAD

**Issue by matgsan** [CitizensDev/CitizensAPI#30]
I tried to use custom skin texture on my NPC and i was not able to do it.
How can I do it?

**Comment by mcmonkey4eva** [comment]
`/npc skin <player name>` optionally add `-p` to make it persist

**Comment by matgsan** [comment]
I want using the API
Already Tried that but its not working.

        VIP.data().set(NPC.PLAYER_SKIN_UUID_METADATA, "MalinaWeissman");
        VIP.data().set(NPC.PLAYER_SKIN_USE_LATEST, false);

Also i tried to put the texture and signature  VIP.data().set(NPC.PLAYER_SKIN_TEXTURE_PROPERTIES_METADATA, "eyJ0aW1lc3RhbXAiOjE0OTkyOTg4NjA5MDgsInByb2ZpbGVJZCI6ImY2OTBmZjQwNmIzNjRiZWZhMmQ1Yzk4OTBiNDM1OTgwIiwicHJvZmlsZU5hbWUiOiJNYWxpbmFXZWlzc21hbiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWNmMWE3ZTg4ZWRmZTNkYjE5YzdlNjRkZTAzZDZiMjUyMmZhNWYyYjk3NGQxYjM3MmE2ZTlmYWFjNTYzZjdlNSJ9fX0=");
        VIP.data().set(NPC.PLAYER_SKIN_TEXTURE_PROPERTIES_SIGN_METADATA, "ArJ/54BRCOE3IF0zFPod1xbgz59Q6FDvxhO+5DUjOWOy54BRfTPqy2NOKCOUddPS4ItvGl9SFRpjDx2SugVW/EBGlmMbg2p/fHemJBKdU55tLoNIySyBrJUtq7E3i9+q1Os8QAgrYEWBpZZpZ/6GVWmZ+kY/lV707LQzBBeMRZCCZau4ANr+uh3WEUkuvfW0ek3O8jGuuqWRfLZLIrtgL5NA2RCLXJDAgSyJ+d2iACdVCxh2qcyov61BdU6E7t81L4O6dF45b0/LiKPw1PK66MtfIq91BkfOtFWg3lKQngNLcjHh3xJuovbASNYJraiykN56P67O/vVsQp1BuPRJU4sE7BL8GWC4WjNnO6uznWEZuZhROKZcY/63t6sI+oOfhIWhozX/y1WXAiq3m+gbSvPmiVoXP1uHKMFV0nOHjLcprflgVuWQaXXCmSVglKTTNa2E3gVIhHYNVdCwd+aZ2IjedQq/gsrnO9VNRyNT21RwmBGNx1lEoVZp1FiOGodAMaSYm9EvDvaJtmcU10PPusedmbavt5Vz2gdAhFxfi4HkBVsTM/Z8WlHIBmUy9IzxJZVe0+hst8Q5Lw8ATGMMDP0X9X9tGY+Qu7IoSJ3qQ3saRKXghu2udssUmrloLpk/V168k7O90iSmHHHp1e1iiaBp5XWJcBoaH9v/b6RInow=");
        and its not working also

**Comment by matgsan** [comment]
@mcmonkey4eva Do you know?

**Comment by games647** [comment]
Any news?

**Comment by matgsan** [comment]
Nothing

**Comment by mcmonkey4eva** [comment]
Sorry, our lead developer would be the one to know, and he's incredibly busy with life right now...

**Comment by games647** [comment]
Okay I got it working. You have to trigger a skin refresh or rejoin the game. 

Requires the normal Citizens project as maven dependency. :disappointed: 
```java
        // set skin properties
        NPC npc = CitizensAPI.getNPCRegistry().getById(0);
        npc.data().setPersistent(NPC.PLAYER_SKIN_UUID_METADATA, "games647");
        npc.data().setPersistent(NPC.PLAYER_SKIN_USE_LATEST, false);

        // send skin change to online players
        Entity npcEntity = npc.getEntity();
        if (npcEntity instanceof SkinnableEntity) {
            ((SkinnableEntity) npcEntity).getSkinTracker().notifySkinChange(npc.data().get(NPC.PLAYER_SKIN_USE_LATEST));
        }
```

Or you respawn the NPC (works with the normal API version):
```java
        NPC npc = CitizensAPI.getNPCRegistry().getById(0);
        npc.data().setPersistent(NPC.PLAYER_SKIN_UUID_METADATA, "Notch");
        npc.data().setPersistent(NPC.PLAYER_SKIN_USE_LATEST, false);

       if (npc.isSpawned()) {
            Location loc = npc.getStoredLocation();
            npc.despawn();
            npc.spawn(loc);
        }
```

**Comment by mcmonkey4eva** [comment]
`Requires the normal Citizens project as maven dependency.`
Yes. That's how you're supposed to link Citizens...

... And yes the entity must respawn for it to apply...

**Comment by games647** [comment]
>Yes. That's how you're supposed to link Citizens...

Doesn't the API version exist for that reason?

**Comment by mcmonkey4eva** [comment]
Nope! The API thing is more of an internal organization thing than anything anyone else needs to interact with.
