### ISSUE TITLE
NPC Navigator Errors

### ISSUE THREAD

**Issue by LokksGaming** [CitizensDev/CitizensAPI#31]
Hi i'm using the api and i'm trying to make it when an npc spawns, it automatically walks to a certain x, y, z, coord in the world. I used this code here: `            if (args[0].equalsIgnoreCase("start")) {
                NPCRegistry registry = CitizensAPI.getNPCRegistry();
                NPC blueKing = registry.createNPC(EntityType.PLAYER, "Blue King");
                Location spawnPlace = new Location(Bukkit.getWorld("E1"), 0, 100, 0, 0, 0);
                Location movePlace = new Location(Bukkit.getWorld("E1"), 10, 100, 0, 0, 0);
                blueKing.spawn(spawnPlace);
                blueKing.getNavigator().setTarget(movePlace);` The NPC is created fine but it doesn't move to the coordinates i want it to. It just stays there and does nothing. Please help.

**Comment by mcmonkey4eva** [comment]
Please open issues at https://github.com/CitizensDev/Citizens2/issues not here.
