### ISSUE TITLE
Many missing Traits

### ISSUE THREAD

**Issue by harm27** [CitizensDev/CitizensAPI#32]
Hi, 

Is there a plan for adding more traits to the CitizensAPI from the main plugin?
Since currently there are only a limited Traits available in the CitizensAPI.
And maybe even more functionality that is available for people trough Citizens commands but not trough the API.
Or do i then need to use the Citizens2 plugin to get access to those additional Traits and functionality. 

Harm (Harm27)

**Comment by mcmonkey4eva** [comment]
You should generally link Citizens2 from maven rather than CitizensAPI, just to get full functionality.

**Comment by harm27** [comment]
Okay, thanks, then i will do that.
