### ISSUE TITLE
Sequence is resetting the executingIndex to 0 when it should be resetting it to -1

### ISSUE THREAD

**Issue by ykgamma** [CitizensDev/CitizensAPI#34]
for net.citizensnpcs.api.ai.tree.Sequence, when selectNext is called, it increments the executingIndex before it gets the value. 

Thus, when executingIndex is reset to 0 with reset(), ++executingIndex return 1, causing the sequence to always skip the first behaviour.

Changing the executingIndex to be set back to -1 like in the constructor would fix this issue.

**Comment by fullwall** [comment]
Fixed, thanks
