### ISSUE TITLE
Hi I'm getting this error and can't load the plugin please help using 1.12.2!My plugins listed below also.

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/CitizensAPI#40]
`[22:59:36] [Server thread/ERROR]: Could not load 'plugins\citizensapi-2.0.22-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[patched_1.12.2.jar:git-Paper-1431]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) [patched_1.12.2.jar:git-Paper-1431]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) [patched_1.12.2.jar:git-Paper-1431]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:226) [patched_1.12.2.jar:git-Paper-1431]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1431]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more`

`[23:02:15 INFO]: Plugins (94): ActionHealth, AdminPlayerMenu, AdvancedPortals, AlwaysOnline, AutoUpdaterAPI, BlockStatus, BottleRecycling, Broadcaster, ChangeSkin, Citizens, CityWorld, ColoredAnvils, CombatTagPlus, CommandPrompter, Craftconomy3, CS-CoreLib, CustomSoundManagerAPI, DamageIndicator, DeathFeathers, DeluxeChat, DeluxeMenus, DiscordSRV, DragonEggRespawn, DyeableSwords, DynamicSigns, EazyEmojis-Lite, EditableSign, Essentials, EssentialsChat, EventSounds, FirstJoinPlus, fly-permission, FOLFriends, ForceResourcepacks, gravy, HolographicDisplays, icJukeBox, InfoBook, InventoryFullPlus, InventoryOverflow, InventoryTweaks, LastHolo, LibsDisguises, LuckPerms, MaintenanceSpigot, Mentions.gg, MoneyDrop, MultiInv, Multiverse-Core, Multiverse-Portals, MVdWPlaceholderAPI, NoPos, NpcSkin, numberKeyBind, OnlinePlayersMenu, OpenAudioMc, OpenInv, PacketListenerApi, ParadiseLand, PerPlayerDrops, PlaceholderAPI, PluginManagerReloaded, Protectiontime, ProtocolLib, Questioner, RealisticLiquid, RealisticMC, SecurityVillagers, Sentinel, ShulkerBoxPlus, SilkSpawners, SimpleSit, Skript, StackableItems, SuperTrails, TabList, TitleManager, Towny, TownyChat, TownyNameUpdater, TownyTitle, TradeMe, Trails, UltimateDrugs, UltimateTrash, UltimateTroll, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard`

**Comment by mcmonkey4eva** [comment]
You somehow mistakenly downloaded the Citizens API (a developer tool). Remove that jar. You only need the Citizens2 jar (which is what runs on your server).

Download link for reference is at http://ci.citizensnpcs.co/job/Citizens2/

**Comment by axemwa** [comment]
oh thanx but someone told me I needed to get citizensapi to get blacksmnith trait working as I get an error for that too and it wont load

**Comment by mcmonkey4eva** [comment]
Whoever told you that was wrong.
Citizens basic user support is available at https://discord.gg/Q6pZGSR

**Comment by axemwa** [comment]
ok thankyou much appreciated
