### ISSUE TITLE
Citizen API ItemStack

### ISSUE THREAD

**Issue by Elytes** [CitizensDev/CitizensAPI#43]
Hi !
Was using Citizen API for my plugin, and I just saw that LivingEntity.getEquipment().setHelmet(ItemStack) etc ... wasn't working when npc is instance of Human entity but work if it's instance of Zombie or other mobs, is there a way to do it or it's a bug ?
Thanks

**Comment by mcmonkey4eva** [comment]
Please open issues at https://github.com/CitizensDev/Citizens2/issues not here.
