### ISSUE TITLE
Creating a custom data store separating npc per file

### ISSUE THREAD

**Issue by Silthus** [CitizensDev/CitizensAPI#44]
I want to create a custom data store where NPCs can be loaded by single files scattered accross multiple sub directories. The primary key would be the path to the file instead of an unique to int id.

Is this possible with the current storage api? Can you give me a short example or hint where I need to start and what classes I need to implement?

Thanks!

**Comment by mcmonkey4eva** [comment]
This package has relevant classes to look into: https://github.com/CitizensDev/CitizensAPI/tree/master/src/main/java/net/citizensnpcs/api/npc
Particularly NPCDataStore as the most important interface to implement, possibly also NPCRegistry

**Comment by mcmonkey4eva** [comment]
Read the docs.
Named: `This is stored in memory with the Citizens plugin, and can be accessed via {@link #getNamedNPCRegistry(String)}.`
Anonymous: `This is not stored by the Citizens plugin.`

**Comment by Silthus** [comment]
I read that, but what does it mean?

**Comment by mcmonkey4eva** [comment]
That means it `can be accessed via {@link #getNamedNPCRegistry(String)}.`

**Comment by mcmonkey4eva** [comment]
Yes

**Comment by Silthus** [comment]
Ok one more question about the integer ids.

I have the following setup: I iterate over any configs in a specific path suffixed by `.npc.yml` and load any config as a single entry in my custom data store. Can I generated a random id per NPC everytime I load my data store?

As long as the IDs stay the same while the server is running everything should be fine, correct? Will Citizens request NPCs by their unique ID or by their integer id?

**Comment by mcmonkey4eva** [comment]
Offhand: I don't think anything will call your registry or datastore except your own code.
I think Citizens doesn't (currently) allow overriding the default NPC store, so any existing plugins or in-game commands will operate on the default store, not yours.

That could probably be made available if you need it - if so, post an issue to the Citizens2 repo instead of here.

**Comment by Silthus** [comment]
Thanks for the help and implementation!

This seems to work now :)
