### ISSUE TITLE
Improved javadocs for Traits

### ISSUE THREAD

**Issue by derteufelqwe** [CitizensDev/CitizensAPI#49]
The output of command /version on my server is: This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
You are 1 version(s) behind
The output of command /version citizens on my server is: Citizens version 2.0.25-SNAPSHOT (build 1675)

The documented / listed Traits by far not all traits available. I found about 3 - 4 Times
as many traits in the source code. But I can't always predict what these traits do (and mabe how to use them) just from the name. 
Adding the missing traits to the docs and adding a short description to all traits would be really helpful.

**Comment by mcmonkey4eva** [comment]
Note that there are two separate packages that each contain traits:
http://jd.citizensnpcs.co/net/citizensnpcs/api/trait/trait/package-summary.html
And http://jd.citizensnpcs.co/net/citizensnpcs/trait/package-summary.html

**Comment by mcmonkey4eva** [comment]
Actually, this is a Citizens issue, it doesn't belong on the CitizensAPI repo
Please post to https://github.com/CitizensDev/Citizens2/issues

First because this issues page isn't used, second because the undocumented traits are all in Citizens itself not this API repo
