### ISSUE TITLE
Citizens disable slpash potion functionality and take 0 damage

### ISSUE THREAD

**Issue by SvetiSuzuki** [CitizensDev/CitizensAPI#64]
Hello. After some testing I figured out that Citizens is the reason splash potions have no affect on my server. I also noticed that out of nowhere, the npcs take 0 damage no matter what I try to damage them with.

**Comment by mcmonkey4eva** [comment]
First: wrong repo, you wanted Citizens2.
Second: regardless, ask for help on Discord @ https://discord.gg/Q6pZGSR
