### ISSUE TITLE
How can I move an NPC?

### ISSUE THREAD

**Issue by Mihis** [CitizensDev/CitizensAPI#67]
My code:
```java
Location spawnLocation;
Location targetLocation;

NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.BAT, "My awesome bat");
npc.spawn(spawnLocation);
if (!npc.isSpawned()) return;
npc.getNavigator().setTarget(targetLocation);
```

But the entity teleports to the target instead of flying to the target.

**Comment by mcmonkey4eva** [comment]
That code is not functional Java.

You've probably edited out the parts of the code that make it work... and also the parts that make it bug. Generally, we can't help with things you don't even post.

----

You likely have invalid locations, or locations too far apart, that are triggering the default teleport-on-stuck behavior. This can be disabled by setting `stuckAction` to `null`, or just making sure the destination is reachable and not farther away than the path-range setting.

----

The `CitizensAPI` issues page should not be use. https://github.com/CitizensDev/Citizens2/issues would be the place to post issues.

However, As this is a basic question, and not really an issue, consider asking for help on Discord: https://discord.gg/Q6pZGSR
