### ISSUE TITLE
maven repo is banned in a country.......

### ISSUE THREAD

**Issue by ham1255** [CitizensDev/CitizensAPI#68]
so basiclly was trying to use maven repo for the plugin api but i wasn't able to download anything so i told myself to load maven repo on web browser and i was greeted with this 
![image](https://user-images.githubusercontent.com/34905970/120826374-6b760000-c56b-11eb-8cac-d09a142e3110.png)

**Comment by mcmonkey4eva** [comment]
Unfortunately we lack the ability to change the minds of the government of the United Arab Emirates. I would recommend contacting your local political revolutionaries. Or something like that. Or use the VPN you have bookmarked there, that'd probably work too.

(We have no part in that message appearing, to be clear, that's something your government did not us)

**Comment by ham1255** [comment]
> Unfortunately we lack the ability to change the minds of the government of the United Arab Emirates. I would recommend contacting your local political revolutionaries. Or something like that. Or use the VPN you have bookmarked there, that'd probably work too.
> 
> 
> 
> (We have no part in that message appearing, to be clear, that's something your government did not us)

Too bad it was banned

**Comment by ham1255** [comment]
Update i guess, after i submitted the form to rereview domain 2 years ago they lifted the ban, it was mistake by there end.

Since other isp didnt have it blocked at that time.
