### ISSUE TITLE
NPCRightClickEvent Not Cancelling

### ISSUE THREAD

**Issue by aarushbhutra** [CitizensDev/CitizensAPI#74]
Hi I am using 1.16.5 to code a plugin and I am trying to cancel NPCRightClickEvent however when I do this

e.getClicker().sendMessage("Hey! Im still talking to you!!");
                        e.setCancelled(true);
                        
                        the task I provided which would run on the NPCRightClickEvent Still runs!

**Comment by fullwall** [comment]
This is not a citizens issue, you need to read how bukkits event api works specifically priorities and ignorecancelled
