### ISSUE TITLE
Faster walking during navigation

### ISSUE THREAD

**Issue by ffd000** [CitizensDev/CitizensAPI#81]
It seems the fastest a NPC or mob can walk is 3x as fast as default speed either through /npc speed or the API. Is it possible a NPC can walk faster than that? Setting base speed or speed modifier really high doesn't make it any faster.

**Comment by mcmonkey4eva** [comment]
Citizens issues would be on https://github.com/CitizensDev/Citizens2/issues but instead of there either, you should post on Discord  https://discord.gg/Q6pZGSR
